name: Actions

on:
 push:
  branches: [master]
  tags:
     - '*'
 pull_request:
  branches: [master]

permissions:
  contents: write

jobs: 
 building:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Adding gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest -b release-1.11.0

  - name: Config
    run: cmake -H. -B ${{github.workspace}}/build -DBUILD_TESTS=ON

  - name: Build
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check
  
  - name: Run program
    run: build/program

  - name: Build package
    run: cmake --build ${{github.workspace}}/build --target package

  - name: Build source package
    run: cmake --build ${{github.workspace}}/build --target package_source

  - name: Make a release
    uses: ncipollo/release-action@v1.11.0
    with:
     tag: v1.0.3
     artifacts: "build/*.deb,build/*.tar.gz,build/*.zip"
     token: ${{ secrets.GITHUB_TOKEN }}
  - name: Artifacts
    uses: actions/upload-artifact@v4
    with:
     name: example
     path: build/example
