name: CPack

on:
  push:
    branches: [master]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [master]

permissions:
  contents: write  # Ensure the workflow has the necessary permissions

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Config ConceptualExample
        run: cmake ${{ github.workspace }} -B ${{ github.workspace }}/build -D PRINT_VERSION=1.0.0

      - name: Build ConceptualExample
        run: cmake --build ${{ github.workspace }}/build

      - name: Build package
        run: cmake --build ${{ github.workspace }}/build --target package

      - name: Package with CPack
        run: |
          cd build
          cpack

      - name: List generated files
        run: ls -l ${{ github.workspace }}/build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ github.workspace }}/packages/*.deb

  create_tag_and_release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ./

      - name: List downloaded files
        run: ls -l ./

      - name: Make a release
        uses: ncipollo/release-action@v1.11.0
        with:
          tag: v1.1.1
          artifacts: "*.deb,*.tar.gz,*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload example artifacts
        uses: actions/upload-artifact@v2
        with:
          name: example
          path: build/example
