name: CPack
on:
  push:
    branches: [master]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [master]
    tags:
      - "v*.*.*"
        
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install CMake
        run: sudo apt-get install -y cmake
      - name: Config ConceptualExample
        run: cmake ${{github.workspace}} -B ${{github.workspace}}/.build/ -D PRINT_VERSION=1.2.0 -D PACK=ON
      - name: Build ConceptualExample
        run: cmake --build ${{github.workspace}}/.build/
      - name: Build package
        run: sudo cmake --build ${{github.workspace}}/.build/ --target package
      - name: Package with CPack
        run: |
          cd ${{github.workspace}}/.build/
          sudo cpack
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: package
      #     path: /packages/*.deb
  # create_tag_and_release:
  #   needs: release
  #   runs-on: ubuntu-latest
  #  steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      # - name: Download artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: package
      #     path: ${{github.workspace}}/.build/
      - name: Make a release
        uses: ncipollo/release-action@v1.11.0
        with:
          tag: v1.4.0
          artifacts: "/packages/*.deb,/packages/*.tar.gz,/packages/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: /packages/
